
#debug: true
spring:
  profiles:
    include: default-user-and-roles
  jackson:
    serialization.indent_output: true
  datasource:
    url: jdbc:mysql://localhost:3306/louis_oauth2_server3?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    name:
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    #        database: h2
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache.use_second_level_cache: true
        cache.use_query_cache: false
        generate_statistics: false
        cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
  resources:
    static-locations:  classpath:/templates/,classpath:/static/
louis:
  token:
    issuer: http:/github.louis.com
    refresh-exp-time: 30
    signing-key: battcn
    expiration-time: 30
  security:
    oauth2:
      clients:
        clientId: admin
        clientSecret: admin
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8089
