spring:
  profiles:
    active: dev
  application:
    name: minaShop
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
  datasource:
    one:
      platform: MYSQL
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: Root
      driver-class-name: com.mysql.cj.jdbc.Driver
    two:
       platform: MYSQL
       url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
       username: root
       password: Root
       driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 9999
  servlet:
    context-path: /mina
debug: true
