spring:

  freemarker:
    expose-request-attributes: true
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates/

  #    suffix: .html
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    sentinel:
      nodes:
        - flux-wms1.cachesit.sfdc.com.cn:8001
        - flux-wms2.cachesit.sfdc.com.cn:8001
        - flux-wms3.cachesit.sfdc.com.cn:8001
      master: FLUX_REDIS_C01
    password: 0qvt1wgi03wnt7x2
  resources:
    static-locations: classpath:/templates/,classpath:/static/
#logging:
#  level:
#      org.springframework: DEBUG
#      com: INFO
mybatis:
  config-location:
server:
  port: 8113
